(define about-template
  (lambda ()
    `(html
      ((head
        (title "About | The White Acre")
        (meta (@ (charset "utf-8")))
        (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
        (link (@ (rel "icon") (href "/static/favicon.ico")))
        (link (@ (rel "stylesheet") (href "/static/style.css")))
        (link (@ (rel "stylesheet") (href "/static/about.css")))
        (link (@ (rel "preconnect") (href "https://fonts.googleapis.com")))
        (link (@ (rel "preconnect") (href "https://fonts.gstatic.com")))
        (link (@ (rel "stylesheet") (href "https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;700&display=block")))
        (link (@ (rel "stylesheet") (href "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css")))
        (script (@ (src "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js")) ""))
      (body
      (div (@ (class "home"))
        (header
          (div (@ (class "wrapper"))
            (a (@ (href "/") (class "logo")) (img (@ (src "/static/logo.svg"))))
              (nav
                (a (@ (href "/about") (class "active")) "About")
                (a (@ (href "/models")) "Models")
                (a (@ (href "/notebooks")) "Notebooks")
                (a (@ (href "/research")) "Papers"))))

        (main
          (div (@ (class "hero"))
            (div (@ (class "overlay")) "")
            (div (@ (class "wrapper"))
              (h1 "About")
              (p "Welcome! My name is Tim Whitaker and I'm a research scientist studying neural network optimization. The White Acre is a website for sharing my latest findings, research papers, and practical insights related to machine learning.")
            )
          )
          (div (@ (class "why"))
            (div (@ (class "wrapper"))
              (div
                (h1 "Research Statement")
                (p "")
                ; (p "I'm really interested in exploring the inner workings of deep neural networks. My PhD research is about neural partitioning, which is the process of splitting deep neural networks into sparse subnetworks that can be trained, executed, or analyzed independently. My work touches on several powerful topics in machine learning including: low-cost ensemble learning, interpretability methods, network pruning, continual learning, neuroregeneration, evolutionary methods and quantum computation. Check out my research papers to learn more about what I'm working on.")
              (p "I am a computer scientist, researcher and engineer who thrives on the pursuit of knowledge and creating cutting-edge solutions to challenging problems in machine learning and artificial intelligence...")
              )
            )
          )

          (div (@ (class "professional"))
            (div (@ (class "wrapper"))
              (div (@ (class "main-header"))
                (h1 "Education")
                (div
                  (img (@ (src "/static/chico-seal.png")))
                  (img (@ (src "https://upload.wikimedia.org/wikipedia/en/thumb/3/33/Colorado_State_University_seal.svg/1200px-Colorado_State_University_seal.svg.png"))))
              )

              (div (@ (class "education"))
                (div (@ (class "item"))
                  (div (@ (class "header"))
                    (p "Doctor of Philosophy in Computer Science")
                    (span "Expected May 2023"))
                  (p "Colorado State University")
                  (p "Dissertation: Neural Partitioning and Subnetwork Ensembles"))
                (div (@ (class "item"))
                  (div (@ (class "header"))
                    (p "Master of Science in Computer Science")
                    (span "May 2021"))
                  (p "Colorado State University")
                  (p "Thesis: Low-Cost Ensemble Learning with Deep Neural Networks"))
                (div (@ (class "item"))
                  (div (@ (class "header"))
                    (p "Bachelor of Science in Computer Science")
                    (span "May 2015"))
                  (p "California State University, Chico")
                  (p "Capstone: Real Time Web Performance Analysis"))

                (div (@ (class "item"))
                  (h3 "Relevant Coursework")
                  (p "Machine Learning, Artificial Intelligence, Object-Oriented Programming, Compiler Design, Software Engineering, Algorithms and Data Structures, Numerical & Parallel Programming, High Performance Computing, Linear Algebra for Data Science, Probability and Statistics"))
                (div (@ (class "item"))
                  (h3 "Notable Things")
                  (p "Member of IEEE")
                  (p "Member of ACM")
                  (p "Recipient of The Artificial Intelligence and Evolutionary Computation Fellowship")
                  (p "Presenter and Technical Committee Member at international conferences including: AAAI, IJCNN, and GECCO")
                )
              )
            )
          )

          
          ; (div (@ (class "timeline"))
          ;   (div (@ (class "wrapper"))
          ;     (ul 
          ;       (li "1992: Born in Florida")
          ;       (li "1996: Got a Nintendo 64 which started a lifelong affair with video games and programming")
          ;       (li "1997: Deep Blue defeats Garry Kasparov")
          ;       (li "1997: Moved to New Orleans, Louisiana")
          ;       (li "2012: Went on my first outdoor climbing trip")
          ;       (li "2015: Graduated from Chico State University with a B.S. in Computer Science")
          ;       (li "2017: Built my first computer")
          ;       (li "2018: Climbed my first V10")
          ;       (li "2020: Graduated from Colorado State University with an M.S. in Computer Science")
          ;       (li "2021: Published my first paper (Prune and Tune Ensembles) at AAAI")
          ;       (li "2022: Got married to my best friend")
          ;     )
          ;   )
          ; )

          ; (div (@ (class "hero3"))
          ;   (div (@ (class "overlay")) "")
          ;   (div (@ (class "wrapper"))
          ;     (h1 "I love to play chess")
          ;     (p "...")
          ;   )
          ; )

          ; (div (@ (class "hobbies"))
          ;   (div (@ (class "wrapper"))
          ;     (h1 "Hobbies")
          ;     (p "I'm an avid rock climber...")
          ;   ))

          (div (@ (class "gallery"))
            (div (@ (class "item"))
              (img (@ (src "/static/wormturns.jpg"))))
            (div (@ (class "item"))
              (img (@ (src "/static/midnight.png"))))
            (div (@ (class "item"))
              (img (@ (src "/static/midnight.png"))))
            (div (@ (class "item"))
              (img (@ (src "/static/getting-ready.jpg"))))
            (div (@ (class "item"))
              (img (@ (src "/static/ceremony.jpg"))))
            (div (@ (class "item"))
              (img (@ (src "/static/saigon.jpg"))))
            (div (@ (class "item"))
              (img (@ (src "/static/rmnp.jpg"))))
            (div (@ (class "item"))
              (img (@ (src "/static/evilution.jpg"))))
          "" )

          
          (footer
            (div (@ (class "wrapper"))
              (div (@ (class "column"))
                (h2 "Site")
                (a (@ (href "/about")) "About")
                (a (@ (href "/models")) "Models")
                (a (@ (href "/notebooks")) "Notebooks")
                (a (@ (href "/research")) "Research"))
              (div (@ (class "column"))
                (h2 "Links")
                (a (@ (href "https://arxiv-sanity-lite.com")) "Arxiv Sanity")
                (a (@ (href "https://paperswithcode.com")) "Papers With Code")
                (a (@ (href "https://news.ycombinator.com")) "Hacker News")
                (a (@ (href "https://www.youtube.com/c/pbsspacetime")) "Space Time"))
              (div (@ (class "column"))
                (h2 "Self")
                (a (@ (href "#")) "CV")
                (a (@ (href "https://github.com/tjwhitaker")) "Github")
                (a (@ (href "https://lichess.org/@/tjwhitaker")) "Lichess")
                (a (@ (href "https://orcid.org/0000-0003-3792-3901")) "Orcid")
                ))))))))))