(define home-template
  (lambda ()
    `(html
      ((head
        (title "Wittes Ende")
        (meta (@ (charset "utf-8")))
        (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
        (link (@ (rel "icon") (href "/static/favicon.ico")))
        (link (@ (rel "stylesheet") (href "/static/home.css")))
        (link (@ (rel "stylesheet") (href "https://fonts.googleapis.com/css?family=Fira+Mono:400,500,700|&display=swap")))
        (link (@ (rel "stylesheet") (href "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css")))
        (script (@ (src "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js")) ""))
      (body
        (div (@ (class "home"))
          (header
            (div (@ (class "wrapper"))
              (a (@ (href "/") (class "logo")) (img (@ (src "/static/logo.svg"))))
              (nav
                (a (@ (href "/blog")) "Blog")
                (a (@ (href "/code")) "Code")
                (a (@ (href "/research")) "Research"))))

          (main
            (div (@ (class "hero"))
              (div (@ (class "overlay")) "")
                (div (@ (class "wrapper"))
                  (h1 "Exploring The Magic Of Machine Learning")
                  (p "Welcome! My name is Tim Whitaker and I'm a computer scientist doing research on neural networks. Wittes Ende is my homepage where you can find out more about me and my work.")))
            
            (div (@ (class "personal"))
              (div (@ (class "content"))
                (div (@ (class "wrapper"))
                  (h1 "About Me")
                  (p "I am a 30 year old computer scientist trying to find my way in this world. I live in Sacramento, California and I just married my best friend, Alyssa, this last year.")
                  (p "I graduated from Chico State University with a B.S. in computer science. I worked as a web developer/software engineer for 5 years before deciding to go back to school to pursue an interest in machine learning and neural networks. I finished my M.S. and am happily pursuing my PhD!")
                  (p "When I am not programming or working on my research, I am probably rock climbing or playing chess!")
                )
              )
              (div (@ (class "image"))
                (img (@ (src "/static/about-me-profile.jpg")))
              )
            )
          
          ; (div (@ (class "low-cost-ensemble-learning"))
            ;   (div (@ (class "wrapper"))
            ;     (div
            ;       (h1 "Low-Cost Ensemble Learning")
            ;       (p "Lorem")
            ;       (a (@ (href "#")) "Read More"))))
            ; (div (@ (class "sparse-perturbations"))
            ;   (div (@ (class "wrapper"))
            ;     (div
            ;       (h1 "Sparse Perturbations for Evolutionary Strategies")
            ;       (p "Lorem")
            ;       (a (@ (href "#")) "Read More"))))
;             (div (@ (class "quote"))
;               (div (@ (class "wrapper"))
;                 (blockquote "\"I do a bit of modeling myself.\"")
;               )
;             )


;             (div (@ (class "intro"))
;               (div (@ (class "wrapper"))
;                 (div (@ (class "column-wrapper"))
;                   (div (@ (class "column"))
;                     (img (@ (src "/static/brain.svg")))
;                     (h2 "Data Science")
;                     (p "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.")
;                   )
;                   (div (@ (class "column"))
;                     (img (@ (src "/static/brain.svg")))
;                     (h2 "ML Research")
;                     (p "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.

; ")
;                   )
;                   (div (@ (class "column"))
;                     (img (@ (src "/static/brain.svg")))
;                     (h2 "Software Engineering")
;                     (p "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.

; ")
;                   )
;                 )
;               )
;             )


          ; (div (@ (class "sequencer")) "")
          ; (div (@ (class "launch-wrapper"))
          ;   (div (@ (class "wrapper"))

          ;   (div (@ (class "player"))
          ;     (div (@ (class "launchpad"))
          ;       (div (@ (class "pad drum") (data-sound "drum.1.1")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.2")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.3")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.4")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.5")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.6")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.7")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.8")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
          ;       (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
          ;       ; (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
          ;       ; (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
          ;       ; (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
          ;       ; (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.1")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.2")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.3")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.4")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.5")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.6")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.7")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.8")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
          ;       (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
          ;       ; (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
          ;       ; (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
          ;       ; (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
          ;       ; (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.1")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.2")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.3")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.4")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.5")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.6")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.7")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.8")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
          ;       (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
          ;       ; (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
          ;       ; (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
          ;       ; (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
          ;       ; (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.1")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.2")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.3")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.4")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.5")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.6")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.7")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.8")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
          ;       ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
          ;       )

          ;     (div (@ (class "options"))
          ;       (h2 "I like to make cool shit")
          ;       (p "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.")
          ;       (p "This is a music tool inspired by Madeon's Adventure Machine.")
          ;       (p "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.")
          ;       (p "Try clicking some buttons over there and press play to make some cool improv music!")
          ;       (div (@ (class "controls"))
          ;         (div (@ (class "play")) "")
          ;         (div (@ (class "stop")) "")
          ;         (div (@ (class "tempo"))
          ;           (p "Tempo") 
          ;           (input (@ (type "text") (value "100")))))))))



            ; (div (@ (class "prune-and-tune-ensembles"))
            ;   (div (@ (class "wrapper"))
            ;     (div
            ;       (h1 "Prune and Tune Ensembles")
            ;       (p "Ensemble Learning is an effective method for improving generalization in machine learning. However, as state-of-the-art neural networks grow larger, the computational cost associated with training several independent networks becomes expensive. We introduce a fast, low-cost method for creating diverse ensembles of neural networks without needing to train multiple models from scratch. We do this by first training a single parent network. We then create child networks by cloning the parent and...")
            ;       (a (@ (href "/static/prune-and-tune-ensembles.pdf") (class "read-more")) "Read More"))))

            ; (div (@ (class "interpretable-diversity-analysis"))
            ;   (div (@ (class "wrapper"))
            ;     (div
            ;       (h1 "Interpretable Diversity Analysis")
            ;       (p "Diversity is an important consideration in the construction of robust neural network ensembles. A collection of well trained models will generalize better to unseen data if they are diverse in the patterns they respond to and the predictions they make. Encouraging diversity becomes especially important for low-cost ensemble methods, as members often share network structure or training epochs in order to avoid training several independent networks from scratch...")
            ;       (a (@ (href "/static/there-is-no-magic-subnetwork.pdf") (class "read-more")) "Read More"))))
            ; (div (@ (class "synaptic-stripping"))
            ;   (div (@ (class "wrapper"))
            ;   (div
            ;     (h1 "Synaptic Stripping")
            ;     (p "Rectified Linear Units (ReLU) have long been the default choice for activation functions in deep neural networks. While they demonstrate excellent empirical performance, ReLU activations can fall victim to the dead neuron problem. In these cases, weights end up being pushed into a state where the neuron outputs zero for all reasonable inputs. Consequently, since the gradient for a dead neuron is zero for all inputs, the weights never update and the neuron can not recover. Inspired by a neurological process of the same name...")
            ;     (a (@ (href "#") ) "Read More"))))
            ; (div (@ (class "quantum-neuron-selection"))
            ;   (div (@ (class "wrapper"))
            ;     (div
            ;       (h1 "Quantum Neuron Selection")
            ;       (p "Gradient descent methods have long been the de facto standard for training deep neural networks. Millions of training samples are fed into models with billions of parameters, which are slowly updated over hundreds of epochs. Recently, it's been shown that large, randomly initialized, neural networks contain subnetworks that perform as well as fully trained models. This insight offers a promising avenue for...")
            ;       (a (@ (href "/static/quantum-neuron-selection.pdf") (class "read-more")) "Read More"))))
                  
          )

          (div (@ (class "contact"))
            (div (@ (class "wrapper"))
              (h1 "Get in Touch")
              (div (@ (class "form-container"))
                (input (@ (placeholder "Name")))
                (input (@ (placeholder "Email")))
                (textarea (@ (placeholder "Message")) "")
                (a (@ (class "button") (href "#")) "Send Message")
              )
              (div (@ (class "map-container"))
                (div (@ (id "map")) "")
                (p "Sacramento, CA")
              )
            )
          )



          (footer
            (div (@ (class "wrapper"))
              (div (@ (class "column"))
                (h2 "Site")
                (a (@ (href "/about")) "About")
                (a (@ (href "/art")) "Art")
                (a (@ (href "/music")) "Music")
                (a (@ (href "")) "Contact"))
              (div (@ (class "column"))
                (h2 "Links")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello"))
              (div (@ (class "column"))
                (h2 "Hello World"))))

          
          (script (@ (src "/static/progressbar.min.js")) "")
          (script (@ (src "/static/howler.min.js")) "")
          (script (@ (src "/static/launchpad.js")) "")
          (script "	mapboxgl.accessToken = 'pk.eyJ1IjoidG13aHRrciIsImEiOiJja2x2NzdpaW0wNXRnMndwOGszNTc3aWd5In0.LvJ2znCQ_1v9a86fxUhQ2A';
          var map = new mapboxgl.Map({
          container: 'map', // container id
          style: 'mapbox://styles/mapbox/streets-v11', // style URL
          center: [-121.4944, 38.5816], // starting position [lng, lat]
          zoom: 10 // starting zoom
          });"
          )
                ))))))
