(define home-template
  (lambda ()
    `(html
      ((head
        (title "Home | Wit's End")
        (meta (@ (charset "utf-8")))
        (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
        (link (@ (rel "icon") (href "/static/favicon.ico")))
        (link (@ (rel "stylesheet") (href "/static/home.css")))
        (link (@ (rel "stylesheet") (href "https://fonts.googleapis.com/css?family=Fira+Mono:400,500,700|&display=swap")))
        (link (@ (rel "stylesheet") (href "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css")))
        (script (@ (src "https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js")) ""))
      (body
      (div (@ (class "home"))
        (header
          (div (@ (class "wrapper"))
            (a (@ (href "/") (class "logo")) (img (@ (src "/static/logo.svg"))))
            (nav 
              (a (@ (href "#")) "What")
              (a (@ (href "#")) "Why")
              (a (@ (href "#")) "How"))
          ))
        (main
          (div (@ (class "hero"))
            (div (@ (class "overlay")) "")
            (div (@ (class "wrapper"))
              (h1 "Handcrafted Artificial Intelligence")
              (p "Passionate about neural network optimization and research.")
              (div (@ (class "button-group"))
                (a (@ (class "button") (href "https://www.twitch.tv/thedeadneuron")) "Contact"))
            ))
            (div (@ (class "projects"))
              (div (@ (class "wrapper"))
                (div (@ (class "project"))
                  (img (@ (src "https://via.placeholder.com/300")))
                )
                (div (@ (class "project"))
                  (img (@ (src "https://via.placeholder.com/300")))
                )
                (div (@ (class "project"))
                  (img (@ (src "https://via.placeholder.com/300")))
                )
              )
            )
          ; (div (@ (class "introduction"))
          ;   (div (@ (class "container"))
          ;     (div (@ (class "slideshow"))
          ;       (div (@ (class "frame"))
          ;         (div (img (@ (src "/static/nucleus-atom-4.svg"))))
          ;         (div (img (@ (src "/static/hexa-cell-2.svg"))))
          ;         (div (img (@ (src "/static/h2o-water-molecule.svg"))))
          ;         (div (img (@ (src "/static/bio-cell.svg"))))
          ;         (div (img (@ (src "/static/methodology-process.svg"))))
          ;         (div (img (@ (src "/static/cell-nucleus.svg"))))
          ;         (div (img (@ (src "/static/dna-helix-1.svg"))))
          ;         (div (img (@ (src "/static/frequency.svg"))))
          ;       )

          ;       (div (@ (class "frame"))
          ;         (div (img (@ (src "/static/nucleus-atom-4.svg"))))
          ;         (div (img (@ (src "/static/hexa-cell-2.svg"))))
          ;         (div (img (@ (src "/static/h2o-water-molecule.svg"))))
          ;         (div (img (@ (src "/static/bio-cell.svg"))))
          ;         (div (img (@ (src "/static/methodology-process.svg"))))
          ;         (div (img (@ (src "/static/cell-nucleus.svg"))))
          ;         (div (img (@ (src "/static/dna-helix-1.svg"))))
          ;         (div (img (@ (src "/static/frequency.svg"))))
          ;       )

          ;       (div (@ (class "frame"))
          ;         (div (img (@ (src "/static/nucleus-atom-4.svg"))))
          ;         (div (img (@ (src "/static/hexa-cell-2.svg"))))
          ;         (div (img (@ (src "/static/h2o-water-molecule.svg"))))
          ;         (div (img (@ (src "/static/bio-cell.svg"))))
          ;         (div (img (@ (src "/static/methodology-process.svg"))))
          ;         (div (img (@ (src "/static/cell-nucleus.svg"))))
          ;         (div (img (@ (src "/static/dna-helix-1.svg"))))
          ;         (div (img (@ (src "/static/frequency.svg"))))
          ;       )
          ;     )
          ;   )
          ; )
          ; (div (@ (class "contributions"))
          ;   (div (@ (class "wrapper"))
          ;     (div (@ (class "column"))
          ;       (img (@ (src "https://absurd.design/assets/img/chapter1/gallery-color-69-8.jpg")))
          ;       (div (@ (class "content"))
          ;       (h3 "Innovative Ideas")
          ;       (p "Dream of the mind's eye finite but unbounded white dwarf Flatland Drake Equation radio telescope. The ash of stellar alchemy are creatures of the cosmos at the edge of forever emerged into consciousness two ghostly white figures in coveralls and helmets are softly dancing Rig Veda."))
          ;     )
          ;     (div (@ (class "column"))
          ;       (img (@ (src "https://absurd.design/assets/img/chapter1/gallery-color-69-16.jpg")))
          ;       (div (@ (class "content"))
          ;         (h3 "Deep Analysis")
          ;         (p "Are creatures of the cosmos the only home we've ever known a billion trillion science muse about hearts of the stars? With pretty stories for which there's little good evidence extraordinary claims require extraordinary evidence culture permanence of the stars intelligent beings encyclopaedia galactica?"))
          ;       )
          ;     (div (@ (class "column"))
          ;       (img (@ (src "https://absurd.design/assets/img/chapter1/gallery-color-69-34.jpg")))
          ;       (div (@ (class "content"))
          ;         (h3 "Creative Applications")
          ;         (p "Cosmos explorations hearts of the stars circumnavigated science as a patch of light. Intelligent beings Apollonius of Perga the only home we've ever known preserve and cherish that pale blue dot finite but unbounded stirred by starlight.")
          ;       )
          ;     )
          ;   )
          ; )
          ; (div (@ (class "showcase"))
          ;   (div (@ (class "wrapper"))
          ;     (blockquote "\"We're like Agadmator, but for machine learning.\"")
          ;     (div (@ (class "video-wrapper"))
          ;       (iframe (@ (width "560") (height "315") (src "https://player.twitch.tv/?channel=thedeadneuron&parent=deadneuron.com") (frameborder "0") (allow "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture")) "")
          ;     )
          ;   )
          ; )
          (div (@ (class "the-problem"))
            (div (@ (class "wrapper"))
              (div 
                (h1 "Hello World")
                (p "Cosmos explorations hearts of the stars circumnavigated science as a patch of light. Intelligent beings Apollonius of Perga the only home we've ever known preserve and cherish that pale blue dot finite but unbounded stirred by starlight."))
            )
          )
          (div (@ (class "the-idea"))
            (div (@ (class "wrapper"))
              (div 
                  (h1 "Hello World")
                  (p "Cosmos explorations hearts of the stars circumnavigated science as a patch of light. Intelligent beings Apollonius of Perga the only home we've ever known preserve and cherish that pale blue dot finite but unbounded stirred by starlight."))
            )
          )
          (div (@ (class "contact"))
            (div (@ (class "wrapper"))
              (h2 "Get in Touch")
              (div (@ (class "form-container"))
                (input (@ (placeholder "Name")))
                (input (@ (placeholder "Email")))
                (textarea (@ (placeholder "Message")) "")
                (a (@ (class "button") (href "#")) "Send Message")
              )
              (div (@ (class "map-container"))
                (div (@ (id "map")) "")
                (p "Sacramento, CA")
              )
            )
          )
          (footer 
            (div (@ (class "wrapper"))
              (div (@ (class "column"))
                (h2 "Site")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")

              )
              (div (@ (class "column"))
                (h2 "Links")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")

              )
              (div (@ (class "column"))
                (h2 "Hello World")
              )
            )
          )

          (script "	mapboxgl.accessToken = 'pk.eyJ1IjoidG13aHRrciIsImEiOiJja2x2NzdpaW0wNXRnMndwOGszNTc3aWd5In0.LvJ2znCQ_1v9a86fxUhQ2A';
          var map = new mapboxgl.Map({
          container: 'map', // container id
          style: 'mapbox://styles/mapbox/streets-v11', // style URL
          center: [-121.4944, 38.5816], // starting position [lng, lat]
          zoom: 10 // starting zoom
          });"
          )
          )))))))