(define models-template
  (lambda ()
    `(html
      ((head
        (title "Models | Wits End")
        (meta (@ (charset "utf-8")))
        (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
        (link (@ (rel "icon") (href "/static/favicon.ico")))
        (link (@ (rel "stylesheet") (href "/static/style.css")))
        (link (@ (rel "stylesheet") (href "/static/models.css")))
        (link (@ (rel "preconnect") (href "https://fonts.googleapis.com")))
        (link (@ (rel "preconnect") (href "https://fonts.gstatic.com")))
        (link (@ (rel "stylesheet") (href "https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;700&display=block"))))
      (body
        (div (@ (class "home"))
          (header
            (div (@ (class "wrapper"))
              (a (@ (href "/") (class "logo")) (img (@ (src "/static/logo.svg"))))
              (nav
                (a (@ (href "/research")) "Publications")
                (a (@ (href "/models")) "Models")
                (a (@ (href "/notebooks")) "Notebooks"))))
          (main
            (div (@ (class "hero"))
              (div (@ (class "overlay")) "")
              (div (@ (class "wrapper"))
                (h1 "Models")
                (p "A catalog of important neural network architectures through history.")))
            (div (@ (class "catalog"))
              (div (@ (class "wrapper"))
                (div (@ (class "item"))
                  (h1 "Perceptron (1958)")
                  (p (small "Frank Rosenblatt"))
                  (p "Neural network research begins with the first implementation of an artificial neuron called the perceptron. The theory for the perceptron was introduced in 1943 by McCulloch and Pitts as a binary threshold classifier. The first implementation was actually intended to be a machine rather than a program. Photocells were interconnected with potentiometers that were updated during learning with electric motors.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/perceptron.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Neocognitron (1979)")
                  (p (small "Kunihiko Fukushima"))
                  (p "A lesser known piece of history. The earliest inspiration for convolutional neural networks comes from Japan in the midst of the AI winter. A breakthrough development for computer vision, the neocognitron utilizes alternating layers of locally connected feature extraction and positional shift cells.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/neocognitron.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Hopfield Network (1982)")
                  (p (small "John Hopfield"))
                  (p "The Hopfield network is a type of recurrent network based on bidirectional connections between neurons. Hopfield networks are a type of Ising model (also known as spin glass) that use Hebbian learning to train associative memory systems.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/hopfield.pdf")) "Paper")))
                
                (div (@ (class "item"))
                  (h1 "Boltzmann Machine (1985)")
                  (p (small "David Ackley, Geoffrey Hinton, Terrence Sejnowski"))
                  (p "The Boltzmann Machine is a type of probabilistic graph model that consists of binary stochastic units and weights learned through an energy based minimization algorithm called contrastive divergence. The name comes from using the Boltzmann distribution to model the joint probability distribution of the input data.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/boltzmann.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "LeNet (1989)")
                  (p (small "Yann LeCun, Bernhard Boser, John Denker, Donnie Henderson, Richard Howard, Wayne Hubbard, Lawrence Jackel"))
                  (p "LeNet is the earliest introduction of the modern convolutional architecture. It contains three alternating convolutional and pooling layers followed by two fully connected layers. This model was introduced alongside the back propagation algorithm which produced incredible results at the time for image classification.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/lenet.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Echo State Network (2002)")
                  (p (small "Herbert Jaeger"))
                  (p "The echo state network is a type of recurrent architecture that utilizes a reservoir of fixed and randomly weighted connections that remain frozen during training. Only layers outside of the reservoir are optimized. The dynamic behavior of the reservoir generates complex temporal patterns which create an echo of the input signal.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/echo-state.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Liquid State Machine (2004)")
                  (p (small "Wolfgang Maass, Henry Markram"))
                  (p "The liquid state machine is closely related to the echo state network but utilizes a reservoir of randomly connected spiking neurons. The dynamic reservoir produces complex spatio-temporal activation patterns that are read out by linear discriminant units.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/liquid-state.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "AlexNet (2012)")
                  (p (small "Alex Krishevsky, Ilya Sutskever, Geoffrey Hinton"))
                  (p "The model that kickstarted the deep learning revolution. Consisting of eight layers, including five convolutional layers and three fully connected layers. AlexNet was one of the first deep convolutional neural networks to achieve state-of-the-art results on ImageNet. The original implementation split the network over two independent gpus to alleviate challenges with memory at the time.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/alexnet.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Inception (2014)")
                  (p (small "Christian Szegedy, Wei Liu, Yangqing Jia, Pierre Sermanet, Scott Reed, Dragomir Anguelov, Dumitru Erhan, Vincent Vanhoucke, Andrew Rabinovich"))
                  (p "Inception is a deep convolutional network developed by Google researchers. It introduced the concept of inception modules, which are composed of multiple parallel convolutional layers of different kernel sizes to capture different feature scales.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/inception.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "ResNet (2016)")
                  (p (small "Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun"))
                  (p "Residual Networks popularized skip connections in deep networks to alleviate vanishing gradient problems. The shortcut connections between blocks allows the gradients to flow directly from later layers to earlier layers, enabling depths of over a hundred layers.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/resnet.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "DenseNet (2016)")
                  (p (small "Gao Huang, Zhuang Liu, Laurens van der Maaten, Kilian Weinberger"))
                  (p "DenseNet builds on top of the ideas introduced in residual networks by implementing skip connections between a given layer and every other successive layer following it. Each layer receives a concatenation of all the feature maps of all the layers preceding it. This allows for learning at different levels of abstraction throughout the network.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/densenet.pdf")) "Paper")))

                (div (@ (class "item"))
                  (h1 "Transformer (2017)")
                  (p (small "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan Gomez, Lukasz Kaiser, Illia Polosukhin"))
                  (p "These models replace the traditional recurrent and convolutional networks with a self attention mechanism that allows the model to attend to different parts of the input sequence to generate contextual representations. The transformer consists of an encoder and decoder architecture that perform input/output mapping.")
                  (div (@ (class "links"))
                    (a (@ (href "/static/transformer.pdf")) "Paper")))

                  
                ; (ul
                ;   (li "Perceptron (1958)")
                ;   (li "LeNet (1989)")
                ;   (li "Hopfield Networks (1982)")
                ;   (li "Long Short-Term Memory (1989)")
                ;   (li "Boltzmann Machine (1986)")
                ;   (li "Echo State Network (2004)")
                ;   (li "AlexNet (2012)")
                ;   (li "Inception (2014)")
                ;   (li "VGG (2014)")
                ;   (li "ResNet (2015)")
                ;   (li "ResNext (2016)")
                ;   (li "DenseNet (2016)")
                ;   (li "SqueezeNet (2016)")
                ;   (li "MobileNet (2017)")
                ;   (li "Transformer (2017)")
                ;   (li "MLP Mixer (2021)")
                ;   (li "EfficientNet (2019)")
                ;   (li "ConvNext (2022)")
                ; )
              )
            )          
          )
          
          (div (@ (class "reference"))
            (p "Hero images generated with neural networks via " (a (@ (href "https://midjourney.com")) "midjourney") ". This website's " (a (@ (href "https://github.com/tjwhitaker/thewhiteacre")) "source code") " was written entirely in scheme!"))

          (script (@ (src "/static/prism.js")) "")
          (script (@ (src "/static/prism-python.min.js")) "")
          (script (@ (src "/static/prism-julia.min.js")) "")
          (footer
            (div (@ (class "wrapper"))
              (div (@ (class "column"))
                (h2 "Site")
                (a (@ (href "/about")) "About")
                (a (@ (href "/models")) "Models")
                (a (@ (href "/notebooks")) "Notebooks")
                (a (@ (href "/research")) "Research"))
              (div (@ (class "column"))
                (h2 "Links")
                (a (@ (href "https://arxiv-sanity-lite.com")) "Arxiv Sanity")
                (a (@ (href "https://paperswithcode.com")) "Papers With Code")
                (a (@ (href "https://news.ycombinator.com")) "Hacker News")
                (a (@ (href "https://www.youtube.com/c/pbsspacetime")) "Space Time"))
              (div (@ (class "column"))
                (h2 "Self")
                (a (@ (href "#")) "CV")
                (a (@ (href "https://github.com/tjwhitaker")) "Github")
                (a (@ (href "https://lichess.org/@/tjwhitaker")) "Lichess")
                (a (@ (href "https://orcid.org/0000-0003-3792-3901")) "Orcid"))))))))))