(define projects-template
  (lambda ()
    `(html
      ((head
        (title "Projects | The White Acre")
        (meta (@ (charset "utf-8")))
        (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
        (link (@ (rel "icon") (href "/static/favicon.ico")))
        (link (@ (rel "stylesheet") (href "/static/projects.css")))
        (link (@ (rel "preconnect") (href "https://fonts.googleapis.com")))
        (link (@ (rel "preconnect") (href "https://fonts.gstatic.com")))
        (link (@ (rel "stylesheet") (href "https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;700&display=block"))))
      (body
      (div (@ (class "home"))
        (header
          (div (@ (class "wrapper"))
            (a (@ (href "/") (class "logo")) (img (@ (src "/static/logo.svg"))))
              (nav
                (a (@ (href "/about")) "About")
                (a (@ (href "/models")) "Models")
                (a (@ (href "/blog")) "Notebooks")
                (a (@ (href "/research")) "Papers"))))

        (main
          (div (@ (class "hero"))
            (div (@ (class "overlay")) "")
            (div (@ (class "wrapper"))
              (h1 "Projects")
              (p "A collection of stuff I've worked on over the last few years. Many of these are not enough to be turned into full fledged papers, but hopefully they inspire as interesting proof of concepts!")
            )
          )

          
            (div (@ (class "prune-and-tune-ensembles"))
              (div (@ (class "wrapper"))
                (div
                  (h1 "WorldGAN")
                  (p "Ensemble Learning is an effective method for improving generalization in machine learning. However, as state-of-the-art neural networks grow larger, the computational cost associated with training several independent networks becomes expensive. We introduce a fast, low-cost method for creating diverse ensembles of neural networks without needing to train multiple models from scratch. We do this by first training a single parent network. We then create child networks by cloning the parent and...")
                  (a (@ (href "/static/prune-and-tune-ensembles.pdf") (class "read-more")) "Read More"))))

            (div (@ (class "interpretable-diversity-analysis"))
              (div (@ (class "wrapper"))
                (div
                  (h1 "Dueling Synth Pedal")
                  (p "Diversity is an important consideration in the construction of robust neural network ensembles. A collection of well trained models will generalize better to unseen data if they are diverse in the patterns they respond to and the predictions they make. Encouraging diversity becomes especially important for low-cost ensemble methods, as members often share network structure or training epochs in order to avoid training several independent networks from scratch...")
                  (a (@ (href "/static/there-is-no-magic-subnetwork.pdf") (class "read-more")) "Read More"))))
                  
          (div (@ (class "sequencer")) "")
          (div (@ (class "wrapper"))
            (div (@ (class "player"))
              (div (@ (class "launchpad"))
                (div (@ (class "pad drum") (data-sound "drum.1.1")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.2")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.3")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.4")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.5")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.6")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.7")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.8")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
                (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
                ; (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
                ; (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
                ; (div (@ (class "pad drum") (data-sound "drum.1.9")) "")
                ; (div (@ (class "pad drum") (data-sound "drum.1.10")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.1")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.2")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.3")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.4")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.5")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.6")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.7")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.8")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
                (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
                ; (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
                ; (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
                ; (div (@ (class "pad bass") (data-sound "bass.1.9")) "")
                ; (div (@ (class "pad bass") (data-sound "bass.1.10")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.1")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.2")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.3")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.4")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.5")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.6")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.7")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.8")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
                (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
                ; (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
                ; (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
                ; (div (@ (class "pad melody") (data-sound "sounds.1.9")) "")
                ; (div (@ (class "pad melody") (data-sound "sounds.1.10")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.1")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.2")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.3")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.4")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.5")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.6")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.7")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.8")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.9")) "")
                ; (div (@ (class "pad fx") (data-sound "fx.1.10")) "")
                )

              (div (@ (class "options"))
                (h2 "Sample Sequencer")
                (p "This is a music tool inspired by Madeon's Adventure Machine.")
                (div (@ (class "controls"))
                  (div (@ (class "play")) "")
                  (div (@ (class "stop")) "")
                  (div (@ (class "tempo"))
                    (p "Tempo") 
                    (input (@ (type "text") (value "100")))))))))

          (footer 
            (div (@ (class "wrapper"))
              (div (@ (class "column"))
                (h2 "Site")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")

              )
              (div (@ (class "column"))
                (h2 "Links")
                (a (@ (href "")) "Hello")
                (a (@ (href "")) "Hello")

              )
              (div (@ (class "column"))
                (h2 "Hello World")
              )
            )
          )

          (script (@ (src "/static/progressbar.min.js")) "")
          (script (@ (src "/static/howler.min.js")) "")
          (script (@ (src "/static/launchpad.js")) "")))))))